name: Build and Push Latest Docker Image to GHCR

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件（合并 PR 会触发）

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # 允许写入 GitHub Packages (GHCR)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image (Latest)
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ark-object-storage:latest"

          echo "Building and pushing image: $IMAGE_NAME"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t $IMAGE_NAME .